service: DeepCellDatasetsFrontend

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

useDotenv: true

plugins:
  - serverless-s3-sync

custom:
  bucket: datasets.deepcell.org
  s3Sync:
    # A simple configuration for copying static assets
    - bucketName: ${self:custom.bucket}
      localDir: build
      acl: public-read
      deleteRemoved: true

resources:
  Resources:

    DeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket}
