service: SesEmailForwarderService

frameworkVersion: '2'

useDotenv: true

custom:
  bucket: ${env:DEPLOYMENT_BUCKET}
  fromEmail: ${env:FROM_EMAIL}
  forwardedEmail: ${env:FORWARDED_EMAIL}
  receiverEmails: ${env:RECEIVER_EMAILS}
  subjectPrefix: ${env:SUBJECT_PREFIX, ""}
  emailKeyPrefix: ${env:EMAIL_KEY_PREFIX, ""}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 6
  logRetentionInDays: 7 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies. Default is false
    name: ${self:custom.bucket}
    maxPreviousDeploymentArtifacts: 3
    serverSideEncryption: AES256
  deploymentPrefix: serverless # The S3 prefix under which deployed artifacts should be stored. Default is serverless
  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendRawEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "SesForwarderBucket" }, "/*" ] ]  }

  environment:
    FROM_EMAIL: ${self:custom.fromEmail}
    FORWARDED_EMAIL: ${self:custom.forwardedEmail}
    RECEIVER_EMAILS: ${self:custom.receiverEmails}
    SUBJECT_PREFIX: ${self:custom.subjectPrefix}
    EMAIL_KEY_PREFIX: ${self:custom.emailKeyPrefix}
    EMAIL_BUCKET:
      Ref: SesForwarderBucket

package:
  include:
    - src/**
    - handler.js
  exclude:
    - README.md
  individually: true

functions:
  SesEmailForwarder:
    handler: index.handler
    name: SesEmailForwarder
    description: Forward emails sent to FORWARDED_EMAIL to RECEIVER_EMAILS.
    timeout: 10
    memorySize: 128
    package:
      include:
        - index.js
      exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
        - README.md

resources:
  Resources:
    SesForwarderBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 
          Fn::Join: ["", ["ses-forwarder-",{ "Ref" : "AWS::AccountId" }  ] ]
        LifecycleConfiguration:
          Rules:
            - ExpirationInDays: 3
              Status: Enabled

    SesForwarderBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: SesForwarderBucket
        PolicyDocument:

          Version: '2012-10-17'
          Statement:
            - Sid: GiveSESPermissionToWriteEmail
              Effect: Allow
              Principal:
                Service: ses.amazonaws.com
              Action: s3:PutObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::",{"Ref":"SesForwarderBucket" },"/*"]]
              Condition:
                StringEquals:
                  aws:Referer:
                    Ref: AWS::AccountId

  Outputs:
    SesForwarderBucket:
      Description: "SES Forwarder Bucket Name"
      Value:
        Ref: SesForwarderBucket
