version: "3"
services:
  app:
    build: .
    volumes: ['.:/usr/src/app']
    #   - /deepcell_data:/data
    links:
      - mongo
      - mail
    depends_on:
      - mongo
      - mail
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: ${MONGODB_DB:-database}
      MONGODB_HOST: ${MONGODB_HOST:-mongo}
      MONGODB_PORT: ${MONGODB_PORT:-27017}
      # MONGODB_USERNAME: ${MONGODB_USERNAME:-root}
      # MONGODB_PASSWORD: ${MONGODB_PASSWORD:-password}
      # MAIL_USERNAME: ${MAIL_USERNAME:-alice@example.com}
      # MAIL_PASSWORD: ${MAIL_PASSWORD:-secretpassword}
      MAIL_SERVER: ${MAIL_SERVER:-locahost}
      MAIL_PORT: ${MAIL_PORT:-587}

  mongo:
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-database}
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - ./DCD_DB:/data/db
    ports:
      - 27017:27017
