version: "3"
services:
  app:
    build: .
    # volumes:
    #   - /deepcell_data:/data
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: ${MONGODB_DB:-database}
      MONGODB_HOST: ${MONGODB_HOST:-mongo}
      MONGODB_PORT: ${MONGODB_PORT:-27017}

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./DCD_DB:/data/db
    ports:
      - 27017:27017
