version: "3"
services:
  app:
    build: .
    volumes:
      - /deepcell_data:/data
    links:
      - db
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      MONGODB_DB: ''
      MONGODB_HOST: ''
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ''
      MONGODB_PASSWORD: ''

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
