service: EduEmailValidationService

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2 # Default region to be used. Default is "us-east-1"
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 6
  logRetentionInDays: 14 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies. Default is false
    name: deepcell-datasets-public
    maxPreviousDeploymentArtifacts: 3
    serverSideEncryption: AES256

package:
  include:
    - src/**
    - handler.js
  exclude:
    - README.md
  individually: true

functions:
  EduEmailValidation:
    handler: index.handler
    name: EduEmailValidation
    description: Raise an error if the email address is not a .edu domain.
    memorySize: 128
    package:
      include:
        - index.js
      exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
        - README.md

configValidationMode: warn # Modes for config validation. `error` throws an exception, `warn` logs error to console, `off` disables validation at all. The default is warn.
