service: ContactFormEmailService

frameworkVersion: '2'

useDotenv: true

custom:
  bucket: ${env:DEPLOYMENT_BUCKET}
  receiverEmailAddress: ${env:RECEIVER_EMAIL}
  senderEmailAddress: ${env:SENDER_EMAIL}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  timeout: 6
  logRetentionInDays: 7 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies. Default is false
    name: ${self:custom.bucket}
    maxPreviousDeploymentArtifacts: 3
    serverSideEncryption: AES256
  deploymentPrefix: serverless # The S3 prefix under which deployed artifacts should be stored. Default is serverless
  apiGateway:
    shouldStartNameWithService: true
  usagePlan:
    throttle:
      burstLimit: 1
      rateLimit: 1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"
  environment:
    RECEIVER_EMAIL: ${self:custom.receiverEmailAddress}
    SENDER_EMAIL: ${self:custom.senderEmailAddress}

package:
  include:
    - src/**
    - handler.js
  exclude:
    - README.md
  individually: true

functions:
  ContactFormSendEmail:
    handler: index.handler
    name: ContactFormSendEmail
    description: Send an email from SENDER_EMAIL to RECEIVER_EMAIL.
    memorySize: 128
    events:
      - http:
          path: sendemail
          method: post
          cors:
            origin: '*'
    package:
      include:
        - index.js
      exclude: # Specify the directories and files which should be excluded in the deployment package for this specific function.
        - README.md
